In [1]:
from numpy import random

x = random.randint(100)
print(x)

61


In [2]:
x = random.rand()

print(x)

0.4041656228644629


In [3]:
x=random.randint(100, size=(5))
print(x)

[96 29  1  3 90]


In [4]:
x = random.randint(100, size=(3, 5))
print(x)

[[97 87 85 45 80]
 [54 64 26 61 16]
 [77 53 24 22 99]]


In [5]:
x = random.rand(5)
print(x)

[0.09460075 0.33568383 0.00200562 0.29791058 0.33575375]


In [6]:
x = random.rand(3, 5)
print(x)

[[0.48531377 0.60822604 0.52062049 0.23973655 0.67308595]
 [0.075181   0.03271094 0.37267123 0.65576347 0.63709122]
 [0.08032364 0.4174526  0.46763525 0.15976118 0.96887955]]


In [7]:
x = random.choice([3, 5, 7, 9])
print(x)

7


In [8]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[7 9 7 9 3]
 [5 3 5 7 7]
 [3 7 5 5 3]]


In [9]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[7 7 7 7 7 5 5 3 7 7 7 5 5 7 5 7 5 7 7 5 7 7 7 5 7 7 5 3 5 7 7 7 5 7 5 5 7
 5 7 7 7 7 7 7 5 7 7 7 3 3 7 7 7 7 5 7 7 7 7 5 7 7 7 7 5 7 7 3 7 7 3 7 7 7
 7 5 7 7 7 7 7 5 7 7 5 7 7 7 7 7 5 7 5 7 5 7 5 7 7 7]


In [10]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

[[7 5 7 7 5]
 [7 7 5 3 7]
 [7 7 7 3 7]]
